services:
  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: 12341
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"